# NumPy Essentials (Part:1 - Arrays)

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 1.<br>

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br> 

**NumPY stands for? Ans: Numerical Python  
Numpy developed by? Ans: Travis Oliphant**

**I hope that you have already installed NumPy, let's move on a create a new notebook to explore more about NumPy.** <br>

# Numpy Arrays
### `arange()`,  `linspace()`, `zeros()`,  `ones()`, `eye()`, `rand()`, `randn()`, `randint()`
### Methods: `reshape()`, `max()`, `min()`, `argmax()`, `argmin()`<br>
### Attributes: `size, shape, dtype` 
### Indexing & slicing of 1-D arrays (vectors)
###  Indexing & slicing 2-D arrays (matrices)

In [1]:
# Let import NumPy
import numpy as np

NumPy has many built-in functions and capabilities. We will focus on some of the most important and key concepts of this powerful library.

# Numpy Arrays

NumPy arrays will be the main concept that we will be using in this course. These arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [2]:
# Lets create a Python list. 
my_list = [-1,0,1] 

my_list

[-1, 0, 1]

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [3]:
my_array = np.array(my_list)

my_array

array([-1,  0,  1])

In [8]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6],[7,8,9], [4, 5, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 9]]

In [9]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 5, 9]])

In [10]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Syntax: arange([start,] stop[, step,], dtype=None) <br>
* Return evenly spaced values within a given interval. <br>

*Press shift+tab for the documentation.*

In [13]:
np.arange(100) # similar to range() in Python, not including 100  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
# We can give the step
np.arange(3,10,2)

array([3, 5, 7, 9])

In [15]:
# We can give the step and dtype
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>
*Press shift+tab for the documentation.*

In [19]:
# start from 1 & end at 15 with 15 evenly spaced points b/w 1 to 15.
np.linspace(1, 10, 100, retstep=True)

(array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
         1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
         2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
         3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
         4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
         5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
         6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909,  7.1

In [20]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(9, 15, 20, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 9.        ,  9.31578947,  9.63157895,  9.94736842, 10.26315789,
        10.57894737, 10.89473684, 11.21052632, 11.52631579, 11.84210526,
        12.15789474, 12.47368421, 12.78947368, 13.10526316, 13.42105263,
        13.73684211, 14.05263158, 14.36842105, 14.68421053, 15.        ]),
 0.3157894736842105)

In [22]:
np.linspace(1,15,30) # 1-D array 

array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
        3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
        5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
        8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
       10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
       13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ])

## Don't Confuse!
  * <b>arange() takes 3rd argument as step size.<b><br>
  * <b>linspace() take 3rd argument as no of point we want.<b>

In [27]:
x = np.arange(0,16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
x.shape

(16,)

In [37]:
x = x.reshape(4, 2, 2)

In [38]:
x

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [39]:
x.shape

(4, 2, 2)

In [40]:
x = x.reshape(1, 16)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>
*np.random. and then press tab for the options with random*

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [41]:
np.random.rand(5) # 1-D array with three elements

array([0.42404886, 0.19824187, 0.08198844, 0.48841207, 0.22622759])

In [42]:
np.random.rand(6,4)  # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.76871933, 0.51261961, 0.48130835, 0.71102848],
       [0.06652108, 0.58799363, 0.11625852, 0.17706233],
       [0.43811369, 0.32200253, 0.31754504, 0.73647258],
       [0.83400909, 0.04816154, 0.3108735 , 0.16310845],
       [0.44743058, 0.62354141, 0.44524659, 0.14308379],
       [0.88894444, 0.66321063, 0.7529516 , 0.68145767]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>
*Press shift+tab for the documentation.*

In [ ]:
np.random.randn(20, 5)

In [ ]:
normal_array = np.random.randn(1000,1) # no tuple, each dimension as a separate argument
normal_array

In [ ]:
import pandas as pd

df = pd.DataFrame(data=normal_array, columns=['A'])
df

In [ ]:
df['A'].hist(bins=100)

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [49]:
np.random.randint(1, 1444, 5) #returns one random int, 1 inclusive, 100 exclusive

array([ 329,  816,  317,  948, 1280])

In [51]:
np.random.randint(100,500,20).reshape(4,5) #returns ten random int,

array([[423, 218, 184, 322, 171],
       [383, 409, 467, 221, 431],
       [431, 331, 319, 294, 214],
       [281, 342, 353, 281, 216]])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [52]:
# lets create 2 arrays using arange() and randint()
array_ranint = np.random.randint(0,100,10)

In [53]:
array_ranint

array([98, 54, 66, 51, 93, 49, 63, 66, 51, 85])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [54]:
array_ranint

array([98, 54, 66, 51, 93, 49, 63, 66, 51, 85])

In [55]:
array_ranint.min()

49

In [56]:
array_ranint.max()

98

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [57]:
array_ranint.argmax() # index starts from 0

0

In [58]:
array_ranint.argmin()

5

### Attributes
* `size, shape, dtype` 

In [59]:
array_arange=np.arange(16)

In [60]:
# Lets take vector array, array_arange 
array_arange.shape
#reshape_test.shape

(16,)

In [63]:
array_arange.size

16

In [64]:
# Size of the array 
array_arange.itemsize

4

In [65]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [66]:
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
array_arange.shape = (4,4)

In [69]:
array_arange

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
array_arange.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
array_arange

In [ ]:
array_arange.reshape(1,16).shape

### Indexing & slicing of 1-D arrays (vectors)

In [ ]:
# Lets create a simple 1-D NumPy array.
# (we can use arange() as well.) 
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [ ]:
array_1d

In [ ]:
# Getting value at certain index
array_1d[2]

In [ ]:
# Getting a range value
array_1d[0:3]
# array_1d is included in the out to compare and understand

In [ ]:
# Using -ve index 
array_1d[-2]
# array_1d is included in the out to compare and understand

In [ ]:
# Using -ve index for a range 
array_1d[1:-2] # 1 inclusive and -2 exclusive in this case

In [ ]:
array_1d

In [ ]:
# Getting up-to and from certain index -- remember index starts from '0'
# (no need to give start and stop indexes)
array_1d[:2]

In [ ]:
array_1d[2:]

In [ ]:
# Assigning a new value to a certain index in the array 
array_1d[0] = -102

In [ ]:
array_1d
# The first element is changed to -102

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [ ]:
array_2d = np.arange(24)
array_2d = array_2d.reshape(6,4)
array_2d

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**. 

We will use `[row,col]`, easier to use comma ',' for clarity.

In [ ]:
# To get a complete row
array_2d[2]

In [ ]:
array_2d[-4] # -0 and 0 is same inedex

In [ ]:
array_2d

In [ ]:
# another way 
row = 5
column = 2
array_2d[row, column]

In [ ]:
# Just to make sure, using [row][col] :)
array_2d[5][2]

In [ ]:
array_2d

In [ ]:
# 2D array slicing
array_2d[:2,:2] # array_2d[:2,:2].shape gives (2,2), 4 elements for top left corner 

### Broadcasting

Numpy arrays are different from normal Python lists because of their ability to broadcast. We will only cover the basics, for further details on broadcasting rules, click [here](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) <br>
Another good read on [broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)!<br>

**Lets start with some simple examples:**

In [ ]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [ ]:
array_1d[0:5] = 500 
array_1d

In [ ]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4), dtype=int)
array_2d

In [ ]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

In [ ]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)  #[0,1,2,3]
# try array_2d + np.arange(0,3), did this work? if not why?

In [ ]:
array_2d * np.arange(0,4)

In [ ]:
array_2d + 300
# array_2d + [300,2], did it work? if not why?

In [ ]:
array_2d

In [ ]:
#array_2d[0, 1]
#array_2d[[0, 1]]
array_2d[[0]]

In [ ]:
array_2d[:,[2]]

In [ ]:
array_2d

In [ ]:
# We can use any order
array_2d[[3,0,1]]

In [ ]:
# lets try another matrix
array_2d = np.arange(24)
array_2d.shape = (6,4)
array_2d

In [ ]:
# grabbing rows
array_2d[[2,3]] #[2][3]

In [ ]:
array_2d[:3, [2,3]]

In [ ]:
# grabbing columns
#array_2d[:,3:2]
array_2d[:,[3,2]]

In [ ]:
# Lets create a simple array using arange()
array_1d = np.arange(1,11)
array_1d

We can apply condition such as >, <, == etc

In [ ]:
array_1d > 3

In [ ]:
# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
bool_array

Lets create a mask to **filter out the even numbers in "array_1d"**

In [ ]:
array_1d % 2

In [ ]:
0 == array_1d % 2

In [ ]:
# A number is even if, number % 2 is "0"
mod_2_mask_1d = array_1d % 2 != 0 
mod_2_mask_1d

In [ ]:
array_1d

In [ ]:
array_1d[mod_2_mask_1d] #array_1d[[False,  True, False,  True, False,  True, False,  True, False,True]]

## NumPy Operations 

Hi Guys,<br>
Welcome to the NumPy Essentials lecture part 2.<br>

Let's talk about NumPy operations in this section, such as:

* <b>Arithmetic operations</b>
* <b>Universal Functions (ufunc)</b>
 

## Arithmetic operations

We can perform arithmetic operations with NumPy arrays. <br>
Let's learn with examples:

In [ ]:
# Let's create an array using arange() method
arr = np.arange(0,5)
arr  

In [ ]:
# Adding two arrays
arr + arr  #[0, 1, 2, 3, 4] + [0, 1, 2, 3, 4]

In [ ]:
# Subtracting two arrays
arr - arr

In [ ]:
# Multiplication
arr * arr

In [ ]:
# Division
arr / arr
# warning and 0/0 is replaced with nan

In [ ]:
1/arr #[0, 1, 2, 3, 4]
# warning for 1/0, inf

In [ ]:
# Power of all the elements in an array
arr ** 2

In [ ]:
# Multiplication with scalar 
2 * arr #[0, 1, 2, 3, 4]

## Universal functions

NumPy have a range of built-in [universal functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html) (ufunc). These are essentially just mathematical operations and we can use them to perform specific task, associate with the function, across the NumPy array.<br>
Let's learn with examples:

In [ ]:
# Square root
np.sqrt(arr) #[0, 1, 2, 3, 4]

In [ ]:
# max and min values
np.max(arr), np.min(arr)

In [ ]:
arr.max()

In [ ]:
# Trigonometric functions, e.g. sin, cos, tan, arcsin, ......
np.sin(arr)

**Generate the follow matrix "array_2d" and replicate the provided outputs.**

In [ ]:
#18a:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d= np.arange(30).reshape(6,5)
array_2d

**Calculate the sum of all the numbers in array_2d?**

In [ ]:
array_2d.sum()

In [ ]:
array_2d.sum(axis=1)

**Calculate sum of all the rows and columns in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
print("Row sum:", array_2d.sum(axis=1))
print("Columns sum:", array_2d.sum(axis=0))

**Calculate the standard deviation of the values in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d.std()

**Create a boolean mask and list out the numbers that are not divisible by 3 in array_2d.**

In [ ]:
# To avoid overwriting the output, please code here 

In [ ]:
array_2d

In [ ]:
array_2d % 3 == 0

In [ ]:
mask_mod_3 = 0 != array_2d % 3
mask_mod_3

In [ ]:
mask_mod_3 = 0 != array_2d % 3  # Creating mask for the said condition
array_2d[mask_mod_3]            # pass the boolean mask to array_2d to return the required results

In [ ]:
np.zeros(5)