# arange

In [6]:
import numpy as np

# np.arange(16).Here 16 means range of 0 to 15 and step 1.

In [10]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
np.arange(0,16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# np.arange(0,100,2).Here 0 is lower limit and 100 is upper limit and 2 is step

In [5]:
 np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Examples

In [12]:
np.arange(5,150)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149])

In [13]:
np.arange(5,150,2)

array([  5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,  29,
        31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
        57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,
        83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107,
       109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133,
       135, 137, 139, 141, 143, 145, 147, 149])

In [14]:
np.arange(5,150,3)

array([  5,   8,  11,  14,  17,  20,  23,  26,  29,  32,  35,  38,  41,
        44,  47,  50,  53,  56,  59,  62,  65,  68,  71,  74,  77,  80,
        83,  86,  89,  92,  95,  98, 101, 104, 107, 110, 113, 116, 119,
       122, 125, 128, 131, 134, 137, 140, 143, 146, 149])

# arange using shape.Here range is 0 to 16 and shape(4,4) means matrix

In [26]:
x=np.arange(0,16)
x.shape=(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
x=np.arange(2,50,2)
x.shape

(24,)

In [34]:
x.shape=(6,4)
x

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

# Example 

In [48]:
x=np.arange(3,97,3)
x

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])

In [49]:
x.shape

(32,)

In [52]:
x.shape=(8,4)
x

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60],
       [63, 66, 69, 72],
       [75, 78, 81, 84],
       [87, 90, 93, 96]])

# arange using reshape

In [53]:
x=np.arange(0,16)
x.reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Example

In [56]:
x=np.arange(0,100,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [57]:
x.shape

(50,)

In [58]:
x.reshape(5,10)

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])