In [1]:
import numpy as np

#1-D zeros and float
np.zeros(16)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [2]:
#2-D zeros that's why two (()) and float
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
#3-D zeros and coverted to int
np.zeros((4,4,4),dtype="int32")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [35]:
#1-D one that's why one ()
np.ones(4)

array([1., 1., 1., 1.])

In [38]:
#3-D one that's why one (())
np.ones((4,4,4),dtype="int32")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [39]:
#Full
np.full((4,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [45]:
np.full((6,3),77)

array([[77, 77, 77],
       [77, 77, 77],
       [77, 77, 77],
       [77, 77, 77],
       [77, 77, 77],
       [77, 77, 77]])

In [41]:
#rand is o to 1 random array but float
np.random.rand(4,2)

array([[0.75284358, 0.08375206],
       [0.40662317, 0.63225936],
       [0.6632167 , 0.78444531],
       [0.19003542, 0.33824829]])

In [44]:
np.random.rand(6,5)

array([[0.55407248, 0.93980532, 0.52397124, 0.80759122, 0.41917121],
       [0.82563933, 0.79691765, 0.34624922, 0.67671731, 0.00924453],
       [0.71029594, 0.28176119, 0.47926233, 0.81164452, 0.99597775],
       [0.36104513, 0.82055876, 0.40257437, 0.80846126, 0.89904125],
       [0.30124779, 0.07441666, 0.59223387, 0.19894788, 0.51596583],
       [0.67296793, 0.56537532, 0.29922052, 0.36041068, 0.7008405 ]])

In [47]:
#randit is int 1 is lower limt 100 is upper limit and quantity=10
np.random.randint(1,100,10)

array([ 9, 58, 30,  5, 34, 88, 53,  2, 29, 95])

In [51]:
##randit is int -1 is lower limt 8 is upper limit and size 
np.random.randint(-1,8, size=(3,3))

array([[2, 2, 0],
       [5, 4, 7],
       [2, 4, 3]])

In [52]:
#randn
np.random.randn(20)

array([ 0.80702974,  0.89920765, -0.27379185, -0.18833877,  2.65696621,
       -0.57816211, -2.08544799, -1.58484494,  0.1999795 ,  0.52610773,
        0.72602917, -1.01479819, -0.77318583, -0.42765198, -0.53364462,
        1.27317258, -0.43160653, -0.74703318, -0.58524011,  1.00341316])

In [53]:
np.random.random(50)

array([0.20499217, 0.98558032, 0.42986123, 0.28327099, 0.94894195,
       0.90297716, 0.15109879, 0.87130474, 0.81591025, 0.62271196,
       0.49889131, 0.24126932, 0.10139952, 0.25503407, 0.02669375,
       0.48118796, 0.13553146, 0.74488607, 0.08169373, 0.97277721,
       0.53258764, 0.54285708, 0.32390462, 0.46993247, 0.36487785,
       0.26453805, 0.81742618, 0.35918629, 0.18225827, 0.94505188,
       0.29510604, 0.9119228 , 0.94073095, 0.73530916, 0.47383881,
       0.39990228, 0.87436296, 0.22654882, 0.03672111, 0.84155714,
       0.23348351, 0.32452075, 0.01542248, 0.68655601, 0.91918032,
       0.08096464, 0.24409619, 0.02184137, 0.58899607, 0.19883091])

In [60]:
np.linspace(1,15,100,retstep=True)

(array([ 1.        ,  1.14141414,  1.28282828,  1.42424242,  1.56565657,
         1.70707071,  1.84848485,  1.98989899,  2.13131313,  2.27272727,
         2.41414141,  2.55555556,  2.6969697 ,  2.83838384,  2.97979798,
         3.12121212,  3.26262626,  3.4040404 ,  3.54545455,  3.68686869,
         3.82828283,  3.96969697,  4.11111111,  4.25252525,  4.39393939,
         4.53535354,  4.67676768,  4.81818182,  4.95959596,  5.1010101 ,
         5.24242424,  5.38383838,  5.52525253,  5.66666667,  5.80808081,
         5.94949495,  6.09090909,  6.23232323,  6.37373737,  6.51515152,
         6.65656566,  6.7979798 ,  6.93939394,  7.08080808,  7.22222222,
         7.36363636,  7.50505051,  7.64646465,  7.78787879,  7.92929293,
         8.07070707,  8.21212121,  8.35353535,  8.49494949,  8.63636364,
         8.77777778,  8.91919192,  9.06060606,  9.2020202 ,  9.34343434,
         9.48484848,  9.62626263,  9.76767677,  9.90909091, 10.05050505,
        10.19191919, 10.33333333, 10.47474747, 10.6